### ISSUE TITLE
Suggested feature: flips

### ISSUE THREAD

**Issue by hagemt** [EvanHahn/ffmpeg-buddy#4]
Support `-vf hflip` for the 'webcam effect' or vertical flip like you do for rotation?

**Comment by EvanHahn** [comment]
That's a good idea. I think it'd go under the "Rotate" option, and would only work if video was enabled.

Is this something that you'd be able to build?

**Comment by hagemt** [comment]
Feel free to land this, if it looks good to you (screenshot in PR); thanks for making this tool!

Edit: total aside, but I have a gist that might interest you at some point:

https://gist.github.com/hagemt/771d6f612167589b42697a35610b649e

**Comment by EvanHahn** [comment]
This was done in d8674b702fc38deda2498bb713311a2ed0fe8fc8 (pull request #5). Closing!
